Create /usr/share/logstash/ so it has correct permissions
When I first ran the state, `/usr/share/logstash/` was not created with executable permissions. This meant that I couldn't start logstash, and got the following errors in `/var/log/upstart/logstash.log`:

    Error: Unable to access jarfile /usr/share/logstash/logstash-latest-monolithic.jar

This is a fix.